export const currencyNames = {
  "AGLD": "Adventurers Gold",
  "FJD": "Фиджийский доллар",
  "LVL": "Латвийский лат",
  "SCR": "Сейшельская рупия",
  "BBD": "Барбадосский доллар",
  "HNL": "Гондурасский лемпира",
  "UGX": "Угандийский шиллинг",
  "KUJI": "Kuji",
  "NEAR": "NEAR Protocol",
  "AIOZ": "AIOZ Network",
  "AUDIO": "Audius",
  "WLD": "Worldcoin",
  "HNT": "Helium",
  "ETHFI": "Ether.fi",
  "FARM": "Farmers World",
  "A8": "A8 Network",
  "SDG": "Суданский фунт",
  "DGB": "DigiByte",
  "AB": "ABBC Coin",
  "BCH": "Bitcoin Cash",
  "AI": "AI Token",
  "FKP": "Фолклендский фунт",
  "JST": "JustStakeIt",
  "HOT": "Hydro Protocol",
  "AO": "AO",
  "AR": "Arweave",
  "B3": "B3Coin",
  "CHILLGUY": "Chill Guy",
  "SEI": "Sei",
  "QAI": "Quantum AI",
  "SEK": "Шведская крона",
  "LION": "Lion",
  "BB": "BigBang",
  "QAR": "Катарский риал",
  "JTO": "Jito",
  "WEMIX": "WEMIX",
  "G": "G Coin",
  "PROMPT": "Prompt",
  "DHN": "DeHub",
  "RLUSD": "Resilient USD",
  "FLR": "Flare",
  "BIGTIME": "Big Time",
  "S": "S Network",
  "BDT": "Бангладешская така",
  "T": "Tu",
  "LYD": "Ливийский динар",
  "W": "W Token",
  "BDX": "BitDEX",
  "BABYDOGE": "Baby Doge Coin",
  "SFP": "SafePal",
  "DIA": "DIA",
  "PORK": "Pig Token",
  "JUP": "Jupiter",
  "RSS3": "RSS3",
  "SNEK": "Snek",
  "LYX": "Lyx",
  "SGB": "Songbird",
  "SGD": "Сингапурский доллар",
  "STRD": "Stride",
  "WOO": "WOO Network",
  "BLUR": "Blur",
  "STRK": "Starknet",
  "WZRD": "Wizard",
  "HRK": "Хорватская куна",
  "DJF": "Джибутийский франк",
  "OMIKAMI": "Omikami",
  "WAVES": "Waves",
  "DOGINME": "Dog in Me",
  "FLOKI": "FLOKI",
  "SHP": "Фунт Святой Елены",
  "BGB": "Baby Grumpy Cat",
  "STEAKUSDC": "Steak USDC",
  "SAND": "The Sandbox",
  "DKK": "Датская крона",
  "WCFG": "Wrapped CFG",
  "QUBIC": "Qubic",
  "BGN": "Болгарский лев",
  "UMA": "Universal Market Access",
  "FOX": "Shapeshift FOX",
  "WSTETH": "Wrapped stETH",
  "TUSD": "TrueUSD",
  "LRDS": "Lords",
  "COOKIE": "Cookie",
  "RBTC": "Wrapped Bitcoin",
  "HTG": "Гаитянский гурд",
  "BHD": "Бахрейнский динар",
  "PUNDIAI": "Pundi X AI",
  "OAS": "Oasis",
  "PEAQ": "peaq",
  "COVAL": "Circuits of Value",
  "ZETACHAIN": "ZetaChain",
  "CGLD": "Celo",
  "UNI": "Uniswap",
  "FX": "FXCoin",
  "HUF": "Венгерский форинт",
  "BIF": "Бурундийский франк",
  "GF": "Green Fuel",
  "PEPECOIN": "PepeCoin",
  "WHITE": "WhiteCoin",
  "WELL": "Wellness",
  "BIO": "BioCoin",
  "SWFTC": "SwftCoin",
  "WAVAX": "Wrapped AVAX",
  "BIT": "Bit",
  "GT": "GateToken",
  "SKK": "Словацкая крона",
  "SKL": "SKALE",
  "UOS": "Ultra",
  "WST": "Самоанский тала",
  "SHPING": "Shping",
  "BRETT": "Brett",
  "SKY": "Skycoin",
  "MYTH": "Myth",
  "DNT": "District0x",
  "HT": "Huobi Token",
  "TRUAPT": "TrueAPT",
  "SLE": "Solana Lite",
  "FLOW": "Flow",
  "UPI": "UPI Token",
  "NTGL": "NetGalleon",
  "SLL": "Сьерра-леоне леоне",
  "SLP": "Smooth Love Potion",
  "ID": "IDEX",
  "DOG": "Dog",
  "GIGA": "Giga",
  "DOP": "Доминиканское песо",
  "IO": "IO Coin",
  "UQC": "Quantum Chain",
  "IP": "Intellectual Property",
  "IQ": "IQ Cash",
  "DOT": "Polkadot",
  "OSAK": "Osaka",
  "1INCH": "1inch",
  "MAD": "MAD",
  "TURBO": "Turbo",
  "BLD": "Bloom",
  "UNFI": "Uniswap Finance",
  "APEX": "Apex",
  "FTM": "Fantom",
  "EVER": "Everscale",
  "POWR": "Power Ledger",
  "FTN": "Futurank",
  "MAV": "Maverick",
  "CORGIAI": "Corgi AI",
  "FTW": "Fortune",
  "ARKM": "Arkham",
  "ATOM": "Cosmos",
  "SAVAX": "Staked AVAX",
  "QUICK": "Quickswap",
  "PENDLE": "Pendle",
  "BLZ": "Bluzelle",
  "BOBA": "Boba Network",
  "TONE": "Tone",
  "BMD": "Бермудский доллар",
  "SNT": "Status",
  "SNX": "Synthetix",
  "KOGE": "Koge",
  "SHIRO": "Shiro",
  "L3": "Layer 3",
  "USD": "Доллар США",
  "API3": "API3",
  "ROSE": "Oasis Network",
  "SATS": "Сатоши",
  "PORTAL": "Portal",
  "SOL": "Solana",
  "MUMU": "MuMu",
  "LA": "LALA World",
  "USR": "Digital USR",
  "SOS": "Somali Shilling",
  "BNB": "Binance Coin",
  "OGN": "Origin Protocol",
  "UST": "TerraUSD",
  "CELR": "Celer Network",
  "CGPT": "ChatGPT",
  "BND": "Brunei Dollar",
  "CELO": "Celo",
  "TBTC": "tBTC",
  "AUCTION": "Auction",
  "LAYER": "Layer",
  "MANTA": "Manta Network",
  "BADGER": "Badger DAO",
  "MULTI": "Multichain",
  "AERO": "Aerodrome Finance",
  "CETUS": "Cetus",
  "SPA": "Spa",
  "BNT": "Bancor",
  "SHDW": "Shade Protocol",
  "SPK": "Spark",
  "BOB": "BOB",
  "MDL": "Молдавский лей",
  "OHM": "Olympus",
  "ME": "ME",
  "SPX": "SPX",
  "MDT": "Measurable Data Token",
  "ANDY": "Andy",
  "AERGO": "Aergo",
  "MOCA": "MoCA",
  "SQD": "Squid",
  "KOIN": "Koin",
  "MX": "MX Token",
  "EGLD": "Elrond",
  "PLUME": "Plume",
  "KAS": "Kadena",
  "TRUMP": "Trump",
  "MEW": "MyEtherWallet",
  "PUNDIX": "Pundi X",
  "AEVO": "Aevo",
  "DADDYCHILL": "Daddy Chill",
  "SRD": "Суринамский доллар",
  "PTGC": "PTGC",
  "NU": "NuCypher",
  "FLUX": "Flux",
  "TOPIA": "Topia",
  "BPX": "BPX",
  "PRCL": "Parcl",
  "QNT": "Quant",
  "OM": "Mantra",
  "ETHW": "EthereumPoW",
  "MUSE": "Muse",
  "ETHX": "EthereumX",
  "OP": "Optimism",
  "CANTO": "Canto",
  "MGA": "Малагасийский франк",
  "OKB": "OKB",
  "WETH": "Wrapped Ethereum",
  "SSP": "Южносуданский фунт",
  "JUPSOL": "Jupiter Solana",
  "NEON": "Neon",
  "MURA": "MurAll",
  "SSV": "SSV Network",
  "PI": "Pi Network",
  "OKT": "OKT Chain",
  "ETH2": "Staked ETH",
  "PAAL": "PAAL AI",
  "KCS": "KuCoin Shares",
  "BUSD": "Binance USD",
  "ARPA": "ARPA Chain",
  "BRL": "Бразильский реал",
  "ALCX": "Alchemix",
  "ALEX": "ALEX",
  "STD": "São Tomé and Príncipe Dobra",
  "STG": "Стеллинг",
  "IOTX": "IoTeX",
  "SHIB": "Shiba Inu",
  "KDA": "Kadena",
  "$MICHI": "Michi",
  "ZAR": "Южноафриканский рэнд",
  "ALEO": "Aleo",
  "STN": "Ston",
  "BSD": "Багамский доллар",
  "STX": "Stacks",
  "QI": "Qi Dao",
  "CAIR": "Cairn",
  "ZBC": "Zebec",
  "BLAST": "Blast",
  "BSV": "Bitcoin SV",
  "IOST": "IOST",
  "SUI": "Sui",
  "CAKE": "PancakeSwap",
  "MSOL": "Marinade staked SOL",
  "OMG": "OMG Network",
  "OMI": "Meme",
  "PYUSD": "PayPal USD",
  "SUN": "Sun",
  "BTC": "Биткойн",
  "UYU": "Уругвайское песо",
  "IOTA": "IOTA",
  "ZYPTO": "Zypto",
  "BTG": "Bitcoin Gold",
  "AIXBT": "AIX Bitcoin",
  "OMR": "Оманский риал",
  "MIR": "MIR",
  "KES": "Кенийский шиллинг",
  "KET": "Karat",
  "BTN": "Бутанский нгултрум",
  "RONIN": "Ronin",
  "SOLVBTC": "SolanaVault BTC",
  "SVC": "Сальвадорский колон",
  "BTT": "BitTorrent",
  "ONE": "Harmony",
  "FWOG": "Frog Wog",
  "RENDER": "Render",
  "ONG": "Ontology Gas",
  "CETH": "Compound Ether",
  "ANKR": "Ankr",
  "ALGO": "Algorank",
  "SYLO": "Sylo",
  "UZS": "Узбекский сум",
  "SC": "Siacoin",
  "SD": "Stable Dollar",
  "ONT": "Ontology",
  "FLUID": "Fluid",
  "DYM": "Dymension",
  "DYP": "DeFi Yield Protocol",
  "WOULD": "Would",
  "MKD": "Македонский динар",
  "DZD": "Алжирский динар",
  "MKR": "Maker",
  "KGS": "Киргизский сом",
  "ICP": "Internet Computer",
  "ZEC": "Zcash",
  "XAF": "Центральноафриканский франк",
  "NEST": "Nest",
  "ICX": "ICON",
  "XAG": "Серебро (в унциях)",
  "KMNO": "KlimaDAO",
  "XAI": "xAI",
  "ZEN": "Horizen",
  "FRIEND": "Friend",
  "DOGE": "Dogecoin",
  "SXP": "Swipe",
  "HBAR": "Hedera",
  "XAU": "Золото (в унциях)",
  "MLN": "Melon",
  "SXT": "StorX",
  "PEPE": "Pepe",
  "KHR": "Камбоджийский риель",
  "IDR": "Индонезийская рупия",
  "DOGS": "Dogs",
  "CTSI": "Cartesi",
  "BWP": "Ботсвана пула",
  "COMAI": "ComAI",
  "OUSG": "Ondo US Dollar Yield",
  "C98": "Coin98",
  "OSMO": "Osmosis",
  "NTRN": "Neutron",
  "SYN": "Synapse",
  "MMK": "Мьянманский кьят",
  "SYP": "Сирийский фунт",
  "CRPT": "Crypterium",
  "SYBTC": "Synth BTC",
  "GAJ": "Gaj",
  "GAL": "Galaxy Digital",
  "GAS": "GAS",
  "XCD": "Восточнокарибский доллар",
  "MMX": "MoneroV",
  "BOME": "BOOK OF MEME",
  "SONIC": "Sonic",
  "VR": "Virtual Reality",
  "XCH": "Chia",
  "SYNC": "Sync",
  "XCG": "XCG",
  "CBBTC": "Coinbase Wrapped BTC",
  "ORA": "Orbit Chain",
  "THETA": "Theta",
  "PANDORA": "Pandora",
  "XCN": "Cryptonex",
  "SZL": "Свазилендский лилангени",
  "ORN": "Orion Protocol",
  "NEXO": "Nexo",
  "AAVE": "Aave",
  "MNT": "Mantle",
  "GBP": "Фунт стерлингов",
  "BONK": "Bonk",
  "BYN": "Белорусский рубль",
  "XDC": "XDC Network",
  "PERP": "Perpetual Protocol",
  "BYR": "Белорусский рубль (старый)",
  "BONE": "Bone",
  "BOND": "BarnBridge",
  "MOG": "Mog Coin",
  "HYPE": "Hype",
  "XDR": "СПЗ (Специальные права заимствования)",
  "SUPEROETH": "Super OETH",
  "TIME": "Time",
  "BICO": "Biconomy",
  "BZD": "Белизский доллар",
  "MOP": "Патака (Макао)",
  "NEWT": "Newt",
  "MONA": "MonaCoin",
  "BBSOL": "Blazestake SOL",
  "MELANIA": "Melania",
  "HMSTR": "Hamster Kombat",
  "XEC": "eCash",
  "UGOLD": "U Gold",
  "PEOPLE": "People",
  "BZR": "Bazar",
  "XT": "XT.com Token",
  "ZIL": "Zilliqa",
  "XEM": "NEM",
  "WEETH": "Wrapped Ether.fi Staked ETH",
  "TRAC": "OriginTrail",
  "MPL": "Maple",
  "10SET": "10SET",
  "WAXL": "WAX",
  "OOKI": "Ooki",
  "SWELL": "Swell",
  "BORA": "Bora",
  "KMF": "Коморский франк",
  "GEL": "Грузинский лари",
  "ZK": "ZK",
  "RSETH": "Rocket Pool Staked ETH",
  "EETH": "Ether.fi Staked ETH",
  "USUAL": "Usual",
  "KEKIUS": "Kekius",
  "KNC": "Kyber Network",
  "PROM": "Prom",
  "ALEPH": "Aleph.im",
  "PONKE": "Ponke",
  "BODEN": "Boden",
  "GFI": "Goldfinch",
  "MRO": "Mero",
  "MRS": "Mars",
  "MRU": "Мавританская угия",
  "BORG": "Borg",
  "WAXP": "WAX",
  "SUKU": "Suku",
  "SWARMS": "Swarm",
  "GGP": "Гернсийский фунт",
  "GRIN": "Grin",
  "VEF": "Венесуэльский боливар",
  "BTRFLY": "Butterfly Protocol",
  "ZMK": "Замбийская квача",
  "MTD": "Metadium",
  "KARRAT": "Karrat",
  "ALPH": "Alpha",
  "MOBILE": "MobileCoin",
  "VINE": "Vine",
  "TAO": "Bittensor",
  "MORPHO": "Morpho",
  "MTL": "Metal",
  "VET": "VeChain",
  "VES": "Венесуэльский боливар (новый)",
  "ZMW": "Замбийская квача",
  "USDG": "USD Gold",
  "KPK": "KPK",
  "LUCE": "Luca",
  "AKUMA": "Akuma",
  "USDT": "Tether",
  "USDC.E": "USD Coin (Ethereum)",
  "OXT": "Orchid",
  "USDS": "USDS",
  "USDP": "Pax Dollar",
  "GHO": "GHO",
  "ILS": "Израильский шекель",
  "ILV": "Illuvium",
  "L1X": "L1X",
  "GHS": "Ганский седи",
  "KPW": "Северокорейский вон",
  "TITS": "Tits",
  "USDY": "Stably USD",
  "USDX": "USDX",
  "EDU": "EduCoin",
  "MEDIA": "Media Network",
  "KEEP": "Keep Network",
  "CAD": "Канадский доллар",
  "EEK": "Эстонская крона",
  "MUR": "Маврикийская рупия",
  "USD1": "USD1",
  "IMP": "Impulse",
  "USD0": "USD0",
  "GIP": "Гибралтарский фунт",
  "BEAM": "Beam",
  "CAR": "Car",
  "IMX": "Immutable X",
  "CAT": "Cat",
  "USDE": "USDe",
  "BARSIK": "Barsik",
  "USDD": "USDD",
  "USDC": "USD Coin",
  "USDB": "USDB",
  "KRD": "KardiaChain",
  "USDA": "USDA",
  "XMON": "Mon",
  "RETH": "Rocket Pool ETH",
  "INJ": "Injective",
  "KRL": "Kryll",
  "VGX": "Voyager",
  "CHEX": "Cheelee",
  "MVR": "Мальдивская руфия",
  "TRIBE": "Tribe",
  "INR": "Индийская рупия",
  "INV": "Inverse",
  "KRW": "Южнокорейская вона",
  "GAME": "Game",
  "TRIBL": "Tribl",
  "KERNEL": "Kernel",
  "STSOL": "Staked SOL",
  "MWC": "MultiWallet Coin",
  "XLM": "Stellar",
  "DORA": "Dora",
  "MWK": "Малавийская квача",
  "EIGEN": "Eigen",
  "SUPER": "Super",
  "KSM": "Kusama",
  "BSC-USD": "BSC USD",
  "RNDR": "Render",
  "ANIME": "Anime",
  "GALA": "Gala",
  "EGP": "Египетский фунт",
  "RAD": "Radicle",
  "MOVE": "Move",
  "MXC": "MXC",
  "TEL": "Telcoin",
  "MOVR": "Moonbeam",
  "RAI": "Rai Reflex Index",
  "XMR": "Monero",
  "MXN": "Мексиканское песо",
  "TET": "Tet",
  "TRIP": "Tripio",
  "MCOIN": "M Coin",
  "CDF": "Конголезский франк",
  "GLM": "Golem",
  "RAY": "Raydium",
  "BTC.B": "Bitcoin (Bridged)",
  "ZORA": "Zora",
  "FDUSD": "First Digital USD",
  "ZRO": "LayerZero",
  "SAROS": "Saros",
  "KUB": "Kub",
  "NPXS": "Pundi X",
  "SSOL": "Staked SOL",
  "IQD": "Иракский динар",
  "GMD": "Гамбийский даласи",
  "RBN": "Ribbon Finance",
  "ZRX": "0x",
  "MYR": "Малайзийский ринггит",
  "CEL": "Celsius",
  "SERAPH": "Seraph",
  "XOF": "Западноафриканский франк",
  "GMT": "STEPN",
  "BEER": "Beer",
  "SWETH": "Staked Wrapped ETH",
  "CET": "Cent",
  "GMX": "GMX",
  "OMNI": "Omni",
  "GNF": "Гвинейский франк",
  "MZN": "Мозамбикский метикал",
  "CFG": "Centrifuge",
  "IRR": "Иранский риал",
  "GNO": "Gnosis",
  "GNT": "Golem",
  "GNS": "Gains Network",
  "XPD": "Палладий (в унциях)",
  "THB": "Тайский бат",
  "XPF": "CFP франк",
  "VANRY": "Vanry",
  "WSTUSR": "Wrapped STUSD",
  "BITCOIN": "Bitcoin",
  "ABT": "Abra",
  "CFX": "Conflux",
  "CDAI": "Compound DAI",
  "KWD": "Кувейтский динар",
  "VELO": "Velodrome",
  "BINK": "Bink",
  "XPT": "Платина (в унциях)",
  "ISK": "Исландская крона",
  "ACH": "Alchemy Pay",
  "MINA": "Mina",
  "TIA": "Celestia",
  "VTHO": "VeThor",
  "DRIFT": "Drift",
  "PAB": "Панамский бальбоа",
  "RED": "Red",
  "ACS": "Access",
  "ACT": "Achain",
  "ACX": "Acala",
  "REI": "Rei",
  "REN": "Ren",
  "ELA": "Elastos",
  "REP": "Augur",
  "ADA": "Cardano",
  "ELF": "Ethereum Lite Fee",
  "REQ": "Request",
  "STORJ": "Storj",
  "VIRTUAL": "Virtual",
  "CHF": "Швейцарский франк",
  "RARI": "Rarible",
  "ELG": "Ethereum Light Gas",
  "ULTIMA": "Ultima",
  "RARE": "SuperRare",
  "LADYS": "Lady",
  "PAXG": "PAX Gold",
  "PAX": "Paxos Standard",
  "REZ": "Rezerve",
  "STBTC": "Staked BTC",
  "GPS": "Global Payment System",
  "XRD": "Radix",
  "CHR": "Chromia",
  "VND": "Вьетнамский донг",
  "CHZ": "Chiliz",
  "KYD": "Каймановы доллары",
  "XRP": "Ripple",
  "JASMY": "JasmyCoin",
  "INDEX": "Index",
  "TJS": "Таджикский сомони",
  "AED": "Дирхам ОАЭ",
  "FIDA": "Bonfida",
  "H2O": "H2O",
  "ZWD": "Зимбабвийский доллар",
  "OCEAN": "Ocean Protocol",
  "QGOLD": "Q Gold",
  "ZWL": "Zimbabwean Stablecoin",
  "PCI": "PCIX",
  "ENA": "Ethena",
  "RGT": "Realio",
  "ENJ": "Enjin Coin",
  "TKX": "Tokenize",
  "YAYSTONE": "Yaystone",
  "KZT": "Казахстанский тенге",
  "YFII": "Yearn.finance",
  "DIMO": "Dimo",
  "GRT": "The Graph",
  "HBTC": "Huobi BTC",
  "INSURANCE": "Insurance",
  "AFN": "Афгани",
  "TFUEL": "Theta Fuel",
  "ENS": "Ethereum Name Service",
  "KAIA": "Kaia",
  "DEGEN": "Degen",
  "JITOSOL": "Jito staked SOL",
  "CKB": "Nervos Network",
  "LUNC": "Terra Classic",
  "XTZ": "Tezos",
  "LUNA": "Terra",
  "AURORA": "Aurora",
  "AGI": "SingularityNET",
  "EOS": "EOS",
  "GST": "GameStars",
  "FORT": "Fort",
  "RIF": "RSK Infrastructure Framework",
  "NAD": "Намибийский доллар",
  "FRXETH": "Frax Ether",
  "DEEP": "Deep",
  "TMM": "TMM",
  "SLERF": "Slerf",
  "GTC": "Gitcoin",
  "PEN": "Перуанский соль",
  "SOLO": "Solos",
  "TMT": "Туркменский манат",
  "CLF": "Californium",
  "TOSHI": "Toshi",
  "HOME": "Home",
  "EUROC": "Euro Coin",
  "SUNDOG": "Sundog",
  "GTQ": "Гватемальский кетсаль",
  "CLP": "Чилийское песо",
  "CPOOL": "Compute Pool",
  "TND": "Тунисский динар",
  "CLV": "Clover Finance",
  "$MYRO": "Myro",
  "XVS": "Venus",
  "MEME": "Meme",
  "W3S": "Web3Space",
  "LYXE": "Lyx",
  "AIC": "AI Crypto",
  "SFUND": "Spartan Fund",
  "TON": "Toncoin",
  "TOP": "Top",
  "ERA": "zkSync Era",
  "PGK": "Папуа-Новой Гвинеи кина",
  "TOR": "Tor",
  "PNUT": "Peanut",
  "GYEN": "GYEN",
  "CNH": "Китайский юань (оффшорный)",
  "NCT": "Pollen",
  "WLUNA": "Wrapped Luna",
  "ERN": "Ethernity Chain",
  "VENOM": "Venom",
  "VOXEL": "Voxel",
  "PHA": "Phala",
  "RLC": "iExec",
  "RLB": "Royal Bank",
  "MAGA": "MAGA",
  "CNY": "Китайский юань",
  "IBERA": "Ibera",
  "PHP": "Филиппинское песо",
  "RLY": "Rarestone",
  "OX_OLD": "Ox",
  "COQ": "Coq Inu",
  "COP": "Колумбийское песо",
  "HOPR": "HOPR",
  "AKT": "Akash",
  "COW": "CoW Protocol",
  "GLMR": "Moonbeam",
  "ORAI": "Oraichain",
  "XYO": "XYO",
  "ETB": "Эфиопский быр",
  "GXC": "GXChain",
  "NEI": "Nei",
  "ETC": "Ethereum Classic",
  "PIP": "Pip",
  "VUV": "Вануату вату",
  "LAK": "Лаосский кип",
  "ETH": "Эфириум",
  "NEO": "Neo",
  "KLAY": "Klaytn",
  "STEAKEURCV": "Staked Euro",
  "ALL": "Албанский лек",
  "MAVIA": "Mavia",
  "HIGH": "High",
  "TRB": "Tellor",
  "CLANKER": "Clanker",
  "ALT": "Alt",
  "ORDI": "Ordinals",
  "GYD": "Гайанский доллар",
  "OSETH": "Stafi Staked ETH",
  "TRU": "TrueFi",
  "VVV": "VVV",
  "WBNB": "Wrapped BNB",
  "AMD": "Армянский драм",
  "GRASS": "Grass",
  "DREP": "Drep",
  "ETHDYDX": "dYdX (Ethereum)",
  "TRY": "Турецкая лира",
  "LBP": "Ливанский фунт",
  "TRX": "Tron",
  "UBTC": "Unlimited Bitcoin",
  "NFT": "NFT",
  "EDGE": "Edge",
  "EUR": "Евро",
  "AMP": "Amp",
  "MEOW": "Meow",
  "ORCA": "Orca",
  "USTC": "TerraClassicUSD",
  "BERA": "Bera",
  "RON": "Румынский лей",
  "NGN": "Нигерийская найра",
  "TST": "Test",
  "CRC": "Коста-риканский колон",
  "PKR": "Пакистанская рупия",
  "VANA": "Vana",
  "CRE": "Credits",
  "LUSD": "Liquity USD",
  "ANG": "Нидерландские антильские гульдены",
  "SPELL": "Spell",
  "LCX": "LCX",
  "CRO": "Crypto.com Coin",
  "PLA": "PlayDapp",
  "TTD": "Доллар Тринидада и Тобаго",
  "SFRXETH": "Staked Frax Ether",
  "CRV": "Curve DAO",
  "MNDE": "Mind",
  "ANT": "Aragon",
  "BAKE": "BakeryToken",
  "RPL": "Rocket Pool",
  "AOA": "Ангольская кванза",
  "PLN": "Польский злотый",
  "AZERO": "Aleph Zero",
  "LDO": "Lido DAO",
  "MAGIC": "Magic",
  "ALICE": "My Neighbor Alice",
  "CORECHAIN": "CoreChain",
  "PLU": "Pluton",
  "SEAM": "Seam",
  "AMAPT": "Aave Matic",
  "CTB": "Crypto Bull",
  "ZEREBRO": "Zerebro",
  "CTC": "Content",
  "NIO": "NIO Token",
  "APE": "ApeCoin",
  "LEO": "LEO",
  "MCO2": "Moss Carbon Credit",
  "00": "Zero",
  "MATIC": "Polygon",
  "APT": "Aptos",
  "APU": "Apus",
  "CTX": "Connect",
  "PNG": "Penguin",
  "TVK": "Terra Virtua Kolect",
  "USYC": "USYC",
  "CUC": "Кубинский конвертируемый песо",
  "PYTH": "Pyth",
  "AI16Z": "AI16Z",
  "CUP": "Кубинский песо",
  "TWD": "Тайваньский доллар",
  "RSD": "Сербский динар",
  "FRAX": "Frax",
  "VRSC": "VerusCoin",
  "WBETH": "Wrapped Beacon ETH",
  "METH": "Morpho staked ETH",
  "BAND": "Band Protocol",
  "POL": "Pol",
  "ASTR": "Astar",
  "NKN": "New Kind of Network",
  "RSR": "Reserve Rights",
  "TWT": "Trust Wallet Token",
  "PARTI": "Particl",
  "ARB": "Arbitrum",
  "CVC": "Civic",
  "ARC": "Arc",
  "VARA": "Vara",
  "CVE": "Civic",
  "SUSDS": "SUSD (Stable USD)",
  "ARK": "Ark",
  "LOKA": "Loot",
  "BTSE": "BTSE",
  "CHEEMS": "Cheems",
  "ARS": "Аргентинское песо",
  "CVX": "Convex Finance",
  "LBTC": "Liquid Bitcoin",
  "MPLX": "Maple",
  "SUSHI": "SushiSwap",
  "PUMP": "Pump",
  "ABTC": "Alien Bitcoin",
  "MANTLE": "Mantle",
  "WBTC": "Wrapped Bitcoin",
  "ASM": "Assembly",
  "RUB": "Российский рубль",
  "AST": "AirSwap",
  "BNSOL": "BNB Staked SOL",
  "MANA": "Decentraland",
  "CSPR": "Casper",
  "AGENTFUN": "Agent Fun",
  "ATA": "Automata",
  "NMR": "Numeraire",
  "STAU": "Stau",
  "JEP": "Джерсийский фунт",
  "NMT": "NMT",
  "ATH": "Ath",
  "LIT": "Lit",
  "JET": "Jet",
  "CGETH.HASHKEY": "CGETH",
  "TNSR": "Tensor",
  "POLYX": "Polymesh",
  "DESO": "Deso",
  "LOOM": "Loom",
  "RVN": "Ravencoin",
  "PRO": "Pro",
  "TZS": "Танзанийский шиллинг",
  "PRQ": "Pragma",
  "ONDO": "Ondo",
  "AUD": "Австралийский доллар",
  "USDT0": "USDT (Zero)",
  "BUIDL": "BUIDL",
  "DEUSD": "DeUSD",
  "MONKEYS": "Monkeys",
  "RWF": "Руандийский франк",
  "KAVA": "Kava",
  "NOK": "Норвежская крона",
  "STRAX": "Stratis",
  "LKR": "Шри-ланкийская рупия",
  "NOT": "Notcoin",
  "NOS": "Nos",
  "CZK": "Чешская крона",
  "AVT": "Avatar",
  "NPC": "NPC",
  "EURC": "Euro Coin",
  "WAL": "Walmart",
  "YER": "Йеменский риал",
  "LSETH": "Liquid Staked ETH",
  "SUSDE": "sUSD (Ethereum)",
  "AWE": "Awe",
  "MASK": "Mask Network",
  "AWG": "Арубанский гульден",
  "NPR": "Непальская рупия",
  "PRIME": "Prime",
  "YFI": "Yearn.finance",
  "MOODENG": "Moo Deng",
  "CWBTC": "Wrapped BTC",
  "KEYCAT": "Keycat",
  "POPCAT": "Popcat",
  "WBT": "Wrapped Bitcoin",
  "LQTY": "Liquity",
  "OLAS": "Olas",
  "ALUSD": "Algorand USD",
  "PUPS": "Pups",
  "FAI": "Fair",
  "PIXEL": "Pixel",
  "ZETA": "ZetaChain",
  "AXL": "Axelar",
  "BILLY": "Billy",
  "CHEEL": "Cheel",
  "PIRATE": "Pirate",
  "YGG": "Yield Guild Games",
  "FARTCOIN": "Fartcoin",
  "CLBTC": "CrossLedger BTC",
  "AXS": "Axie Infinity",
  "SYRUP": "Syrup",
  "HONEY": "Honey",
  "XSOLVBTC": "X Solv BTC",
  "0X0": "0x0",
  "COMP": "Compound",
  "HFT": "Hashflow",
  "WAMPL": "Wrapped AMP",
  "UXLINK": "UXLINK",
  "CMETH": "CoinMarketCap Staked ETH",
  "RUNE": "THORChain",
  "PURR": "Purr",
  "ZEUS": "Zeus",
  "PENGU": "Pudgy Penguins",
  "DEXT": "Dext",
  "FORTH": "Forth",
  "GHST": "Ghast",
  "MATH": "Math",
  "IDEX": "IDEX",
  "DEXE": "Dexe",
  "VNST": "Vietnamese Stablecoin",
  "AVAX": "Avalanche",
  "AZN": "Азербайджанский манат",
  "AMPL": "Ampleforth",
  "GOAT": "Goat",
  "UAH": "Украинская гривна",
  "BANANA": "Banana",
  "WEN": "Wen",
  "NEIRO": "Neiro",
  "LPT": "Livepeer",
  "KAITO": "Kaito",
  "EZETH": "Ether.fi Staked ETH",
  "GODS": "Gods",
  "EDUM": "Edu",
  "PYG": "Парагвайский гуарани",
  "JMD": "Ямайский доллар",
  "XAUT": "XAUT",
  "PYR": "Pyramid",
  "BTRST": "Butter",
  "MKUSD": "MetaKUSD",
  "DAG": "Constellation",
  "BERASTONE": "Bera Stone",
  "LQR": "Liquor",
  "DAI": "Dai",
  "DAO": "DAO",
  "AVAIL": "Avail",
  "DAR": "DAR",
  "FET": "Fetch.ai",
  "CBETH": "Coinbase Wrapped stETH",
  "LRC": "Loopring",
  "REPV2": "Augur",
  "LRD": "Либерийский доллар",
  "CORE": "Core",
  "DASH": "Dash",
  "POKT": "Pokt",
  "SAGA": "Saga",
  "JOD": "Иорданский динар",
  "GUSD": "Gemini Dollar",
  "HKD": "Гонконгский доллар",
  "JOE": "JOE",
  "ARSMEP": "ARS Mep",
  "LSL": "Лесото лоти",
  "LSK": "Lisk",
  "PUMPBTC": "Pump BTC",
  "SAFE": "Safe",
  "RDOG": "Rug Dog",
  "DCR": "Decred",
  "WIF": "Dogwifhat",
  "LTC": "Litecoin",
  "METIS": "Metis",
  "ECOIN": "Ecoin",
  "STETH": "Lido Staked ETH",
  "NXM": "Nexus Mutual",
  "LTL": "Литовский лит",
  "SAR": "Саудовский риял",
  "DYDX": "dYdX",
  "AGIX": "SingularityNET",
  "MUBI": "Mubi",
  "POND": "Marlin",
  "RBNT": "Ruben",
  "JPY": "Японская иена",
  "UFD": "Universal USD",
  "SBD": "Доллар Соломоновых Островов",
  "GRIFFAIN": "Griffain",
  "DDX": "DerivaDEX",
  "LINK": "Chainlink",
  "QTUM": "Qtum",
  "WILD": "Wild",
  "POLS": "Pol",
  "FIL": "Filecoin",
  "POLY": "Poly",
  "EBTC": "Eigenlayer BTC",
  "BAL": "Balancer",
  "BAM": "Конвертируемая марка",
  "BAN": "Banano",
  "FIS": "FIS",
  "BAT": "Basic Attention Token",
  "NZD": "Новозеландский доллар",
  "COTI": "COTI"
};